// react/sohi/src/view/HomePage/components/ArtItem.js
import React, { Component } from 'react';
import '../styles/artItem.less'

class ArtItem extends Component {
  constructor(props) {
    super(props)
    this.state = {}
  }

  filters () {
    return {
      getDate(time) {
        let date = (new Date(time)).getDate()

        return date < 10 ? `0${date}` : date
      },

      getMonth(time) {
        let month = (new Date(time)).getMonth() + 1

        return month < 10 ? `0${month}` : month
      },

      getYear(time) {
        return (new Date(time)).getFullYear()
      }
    }
  }

  render() {
    let { article } = this.props
    let { getDate, getMonth, getYear } = this.filters()

    return (
      <div className="art-item">
        <div className="article clearfix">
          <div className="article-date">
            <span className="date day">{ getDate(article.created) }</span>
            <span className="date month">{ getYear(article.created) }-{ getMonth(article.created) }</span>
          </div>
          <div className="article-main">
            <div className="content">
              <h2>{ article.title }</h2>
              <p>{ article.summary }</p>
              <div className="g-cover">
                <img src={ article.cover } alt={ article.title } />
              </div>
            </div>
            <div className="more">
              <span>更多>>></span>
            </div>
          </div>
        </div>
      </div >
    );
  }
}

export default ArtItem;

// blog/src/view/HomePage/ArtItem.vue
<template>
  <div class="art-item">
    <div class="article clearfix">
      <div class="article-date">
        <a class="day" href="javascript:;">{{article.created | getDate}}</a>
        <a class="month" href="javascript:;">{{article.created | getYear}}-{{article.created | getMonth}}</a>
      </div>
      <div class="article-main">
        <div class="content">
          <h2>
            <a href="javascript:;">{{article.title}}</a>
          </h2>
          <p>{{article.summary}}</p>
          <img v-if="article.cover" :src="article.cover" :alt="article.title">
        </div>
        <div class="more">
          <a href="/">更多>>></a>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ArtItem',
  props: {
    article: {
      required: true,
      type: Object
    }
  },

  filters: {
    getDate (time) {
      let date = (new Date(time)).getDate()

      return date < 10 ? `0${date}` : date
    },

    getMonth (time) {
      let month = (new Date(time)).getMonth() + 1

      return month < 10 ? `0${month}` : month
    },

    getYear (time) {
      return (new Date(time)).getFullYear()
    }
  }
}
</script>

<style lang="less" scoped>
.article {
  padding: 25px 30px;
  background: #fff;
  .article-date {
    float: left;
    a {
      display: block;
      transition: 0.3s;
      &:hover {
        color: #4d4d4d;
        border-color: #4d4d4d;
      }
    }
    .day {
      width: 70px;
      height: 70px;
      border: 5px solid #828d95;
      line-height: 70px;
      text-align: center;
      color: #828d95;
      font-size: 40px;
      border-radius: 50%;
    }
    .month,
    .year {
      text-align: center;
      font-size: 20px;
      line-height: 1.5em;
      color: #c0c0c0;
    }
  }
  .article-main {
    margin-left: 105px;
    .content {
      h2 {
        font-weight: normal;
        a {
          font-size: 24px;
          color: #4c4c4c;
          line-height: 1.5em;
          transition: 0.3s;
          &:hover {
            color: #828d95;
          }
        }
      }
      p {
        font-size: 14px;
        color: #737373;
        line-height: 1.5em;
      }
      img {
        margin: 20px 0;
      }
    }
    .more {
      overflow: hidden;
      a {
        float: right;
        font-size: 16px;
        color: #828d95;
        transition: 0.3s;
        &:hover {
          color: #4d4d4d;
        }
      }
    }
  }
}
</style>
